### ISSUE TITLE
clean_class in ObjectClassifier

### ISSUE THREAD

**Issue by jkli-aa** [yrcong/STTran#18]
Thanx for ur wonderful work.
It seems that the clean_class replaces the categories of those data that originally classified as class_ idx with their second highest confidence categories when it is sgdet mode. Could you explain why this operation performs here?
Thanx again.
Waiting for reply : )

**Comment by yrcong** [comment]
Hi!
We processed like this due to the quality of the dataset. Some categories in the Action Genome are overlapped (somehow seriously), not only semantically but also spatially. For example in one frame there are two boxes respectively annotated as:
class: book  		        bbox:[138.94, 397.36,180.82,419.24]
class:paper/notebook  	bbox:[138.93, 397.54,180.51,419.65]

To avoid the models suffering from this and make the result more convincing, we did this post-processing:)

**Comment by taolunzu11** [comment]
你好，请问ObjectClassifier 中的 clean_class 的 class_idx 为何输入5，8，17呢
